allowBuilds:
  '@tdesign/uniapp': true
  core-js: true
  core-js-pure: true
  esbuild: true
  vue-demi: true
patchedDependencies:
  '@supabase/realtime-js@2.117.1': patches/@supabase__realtime-js@2.117.1.patch
